export const PRESET_CONFIG = {
  Vogue: {
    rationale:
      "Phù hợp editorial cover image có độ quyền lực cao, bố cục sạch, ánh nhìn trực diện, cảm giác bìa tạp chí.",
    styleTokens: [
      "high-fashion editorial portrait",
      "iconic magazine-cover energy",
      "strong cover presence",
      "refined luxury styling",
    ],
    lighting: [
      "polished studio lighting",
      "soft but defined key light",
      "clean facial sculpting",
      "controlled highlights",
    ],
    environment: [
      "minimal studio backdrop",
      "clean negative space",
      "composition suitable for magazine cover",
    ],
    camera: [
      "85mm portrait look",
      "tight editorial crop",
      "clean centered composition",
    ],
    color: [
      "refined contrast",
      "luxury skin tones",
      "subtle film grain",
      "smooth highlight roll-off",
      "natural skin texture",
    ],
    negative: [
      "plastic skin",
      "over-retouched beauty filter",
      "cluttered background",
      "awkward hands",
      "bad anatomy",
      "extra fingers",
      "text artifacts",
      "watermark",
      "logo",
    ],
    params: {
      sampler: "DPM++ 2M Karras",
      steps: 32,
      cfg: 6.5,
      aspectRatio: "4:5",
      seedPolicy: "lock seed for series",
      identityStrength: "high",
    },
  },

  "Dior Chiaroscuro": {
    rationale:
      "Phù hợp brief tối, cinematic, sang trọng, quyền lực; mạnh về shadow, sculptural light và chất liệu cao cấp.",
    styleTokens: [
      "cinematic Dior-inspired fashion editorial",
      "heritage luxury mood",
      "sculptural elegance",
      "dramatic editorial authority",
    ],
    lighting: [
      "chiaroscuro lighting",
      "single directional key light from the side",
      "deep shadow falloff",
      "controlled rim separation",
      "high contrast but elegant",
    ],
    environment: [
      "dark studio or shadowed luxury interior",
      "minimal set with atmospheric depth",
      "deep background separation",
    ],
    camera: [
      "85mm portrait lens look",
      "editorial waist-up or 3/4 framing",
      "cinematic depth of field",
    ],
    color: [
      "deep blacks",
      "rich shadow detail",
      "subtle film grain",
      "smooth highlight roll-off on satin and skin",
      "preserved pores and micro-texture",
    ],
    negative: [
      "flat lighting",
      "cheap glam",
      "plastic skin",
      "overexposed highlights",
      "muddy blacks",
      "text artifacts",
      "watermark",
      "logo",
      "extra fingers",
      "deformed hands",
    ],
    params: {
      sampler: "DPM++ SDE Karras",
      steps: 36,
      cfg: 6.5,
      aspectRatio: "4:5",
      seedPolicy: "lock seed for same identity series",
      identityStrength: "high",
    },
  },

  "Prada Intellectual": {
    rationale:
      "Phù hợp brief tối giản, trí tuệ, hiện đại, lạnh, sang theo hướng architectural và quiet power.",
    styleTokens: [
      "Prada-inspired intellectual fashion portrait",
      "minimalist modernist mood",
      "quiet power",
      "subversive elegance",
    ],
    lighting: [
      "controlled editorial lighting",
      "soft directional key",
      "restrained contrast",
      "clean facial structure",
    ],
    environment: [
      "minimal architectural studio",
      "brutalist or gallery-clean backdrop",
      "austere refined environment",
    ],
    camera: [
      "85mm portrait look",
      "clean editorial framing",
      "precise composition",
    ],
    color: [
      "muted luxury palette",
      "neutral blacks, navy, beige, charcoal",
      "matte-controlled contrast",
      "natural skin texture",
      "fabric realism",
    ],
    negative: [
      "glossy k-pop glow",
      "overly romantic mood",
      "plastic skin",
      "busy set",
      "oversaturated colors",
      "text artifacts",
      "watermark",
      "logo",
      "extra fingers",
    ],
    params: {
      sampler: "DPM++ 2M Karras",
      steps: 30,
      cfg: 6,
      aspectRatio: "4:5",
      seedPolicy: "lock seed, vary pose slightly",
      identityStrength: "high",
    },
  },

  "Balenciaga Raw Flash": {
    rationale:
      "Phù hợp raw luxury, direct flash, anti-polish, brutalist fashion image, cảm giác thật và sắc.",
    styleTokens: [
      "raw luxury fashion portrait",
      "anti-editorial realism",
      "brutalist fashion image",
      "bold attitude",
    ],
    lighting: [
      "direct on-camera flash",
      "hard flash falloff",
      "intense facial definition",
      "minimal fill",
    ],
    environment: [
      "raw concrete or industrial setting",
      "authentic urban texture",
      "unpolished premium environment",
    ],
    camera: [
      "flash snapshot editorial look",
      "slightly aggressive crop",
      "documentary-fashion framing",
    ],
    color: [
      "cool neutral grading",
      "hard contrast",
      "visible texture",
      "real skin detail",
      "minimal retouch",
    ],
    negative: [
      "soft beauty lighting",
      "romantic glow",
      "plastic skin",
      "over-smoothed face",
      "fantasy background",
      "text artifacts",
      "watermark",
      "logo",
    ],
    params: {
      sampler: "Euler a",
      steps: 24,
      cfg: 5.5,
      aspectRatio: "4:5",
      seedPolicy: "semi-locked for raw variations",
      identityStrength: "medium-high",
    },
  },

  "K-pop Glow": {
    rationale:
      "Phù hợp beauty editorial sáng, idol polish, glow sạch, ảnh thời trang mềm và camera-friendly.",
    styleTokens: [
      "K-pop idol editorial portrait",
      "soft charisma",
      "beauty-forward luxury styling",
      "camera-aware elegance",
    ],
    lighting: [
      "beauty clamshell lighting",
      "bright catchlights",
      "soft luminous skin rendering",
      "clean highlight control",
    ],
    environment: [
      "clean studio color field or refined beauty set",
      "polished minimal background",
    ],
    camera: [
      "85mm beauty portrait look",
      "tight flattering crop",
      "clean symmetry",
    ],
    color: [
      "radiant but natural skin tones",
      "soft glow",
      "clean pastel-neutral finish",
      "refined texture preservation",
    ],
    negative: [
      "dark gothic mood",
      "heavy noir shadows",
      "plastic skin",
      "greasy overglow",
      "harsh gritty flash",
      "text artifacts",
      "watermark",
      "logo",
    ],
    params: {
      sampler: "DPM++ 2M Karras",
      steps: 28,
      cfg: 5.8,
      aspectRatio: "4:5",
      seedPolicy: "lock seed for face consistency",
      identityStrength: "high",
    },
  },

  Minimal: {
    rationale:
      "Phù hợp quiet luxury, negative space, tối giản mạnh, gallery-clean và silhouette rõ.",
    styleTokens: [
      "minimalist fashion editorial portrait",
      "quiet luxury",
      "clean lines",
      "editorial restraint",
    ],
    lighting: [
      "soft directional light",
      "gentle shadow gradient",
      "clean facial shape",
    ],
    environment: [
      "plain seamless studio background",
      "strong negative space",
      "gallery-clean composition",
    ],
    camera: [
      "85mm portrait look",
      "waist-up editorial crop",
      "precise framing",
    ],
    color: [
      "neutral refined palette",
      "controlled contrast",
      "subtle grain",
      "natural skin texture",
    ],
    negative: [
      "busy styling",
      "cluttered props",
      "plastic skin",
      "oversaturated color",
      "dramatic set dressing",
      "text artifacts",
      "watermark",
      "logo",
    ],
    params: {
      sampler: "DPM++ 2M Karras",
      steps: 26,
      cfg: 5.8,
      aspectRatio: "4:5",
      seedPolicy: "lock seed",
      identityStrength: "medium-high",
    },
  },

  "Avant-garde": {
    rationale:
      "Phù hợp concept editorial mạnh, tạo hình sculptural, fashion art image và bố cục có ý niệm.",
    styleTokens: [
      "avant-garde fashion editorial portrait",
      "conceptual luxury image",
      "sculptural body language",
      "art-forward styling",
    ],
    lighting: [
      "graphic high-contrast lighting",
      "precise shadows",
      "controlled specular accents",
    ],
    environment: [
      "conceptual set design",
      "editorial art-space atmosphere",
      "idea-driven backdrop",
    ],
    camera: [
      "fashion editorial lensing",
      "bold crop",
      "sculptural framing",
    ],
    color: [
      "art-directed palette",
      "dramatic contrast",
      "intentional texture",
      "natural skin detail retained",
    ],
    negative: [
      "generic glam",
      "commercial catalog look",
      "plastic skin",
      "messy anatomy",
      "random props",
      "text artifacts",
      "watermark",
      "logo",
    ],
    params: {
      sampler: "DPM++ SDE Karras",
      steps: 34,
      cfg: 6.8,
      aspectRatio: "4:5",
      seedPolicy: "lock seed for concept series",
      identityStrength: "medium-high",
    },
  },
};