ALTER TABLE jobs ADD COLUMN is_pilot INTEGER NOT NULL DEFAULT 0;
ALTER TABLE jobs ADD COLUMN case_study_permission INTEGER NOT NULL DEFAULT 0;
ALTER TABLE jobs ADD COLUMN testimonial_permission INTEGER NOT NULL DEFAULT 0;
